// <auto-generated />
using System;
using BackendCoursFlow.Donnees;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace coursFlow.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511065400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Classe", b =>
                {
                    b.Property<int>("IdClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClasse"));

                    b.Property<string>("Groupe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdClasse");

                    b.HasIndex("IdFiliere");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Disponibilite", b =>
                {
                    b.Property<int>("IdDispo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDispo"));

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<int>("IdProf")
                        .HasColumnType("integer");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("IdDispo");

                    b.HasIndex("IdProf");

                    b.ToTable("Disponibilites");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Filiere", b =>
                {
                    b.Property<int>("IdFiliere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFiliere"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdFiliere");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Cours", b =>
                {
                    b.Property<int>("IdCours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCours"));

                    b.Property<string>("AnneeUniversitaire")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duree")
                        .HasColumnType("integer");

                    b.Property<int>("EmploiDuTempsIdEmploi")
                        .HasColumnType("integer");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer");

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer");

                    b.Property<int>("IdProf")
                        .HasColumnType("integer");

                    b.Property<int>("IdSalle")
                        .HasColumnType("integer");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VolumeHoraire")
                        .HasColumnType("integer");

                    b.HasKey("IdCours");

                    b.HasIndex("EmploiDuTempsIdEmploi");

                    b.HasIndex("IdClasse");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdProf");

                    b.HasIndex("IdSalle");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.EmploiDuTemps", b =>
                {
                    b.Property<int>("IdEmploi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmploi"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("HeureDebut")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeureFin")
                        .HasColumnType("interval");

                    b.Property<int>("Jour")
                        .HasColumnType("integer");

                    b.HasKey("IdEmploi");

                    b.ToTable("EmploisDuTemps");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Matiere", b =>
                {
                    b.Property<int>("IdMatiere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMatiere"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credit")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdMatiere");

                    b.ToTable("Matieres");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Prerequis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdMatiere")
                        .HasColumnType("integer");

                    b.Property<int>("IdMatierePrerequis")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdMatiere");

                    b.HasIndex("IdMatierePrerequis");

                    b.ToTable("Prerequis");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Salles.Salle", b =>
                {
                    b.Property<int>("IdSalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalle"));

                    b.Property<string>("Batiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Capacite")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("IdSalle");

                    b.ToTable("Salles");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Admin", b =>
                {
                    b.HasBaseType("BackendCoursFlow.Models.Utilisateurs.Utilisateur");

                    b.Property<int>("IdAdmin")
                        .HasColumnType("integer");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Etudiant", b =>
                {
                    b.HasBaseType("BackendCoursFlow.Models.Utilisateurs.Utilisateur");

                    b.Property<int>("ClasseIdClasse")
                        .HasColumnType("integer");

                    b.Property<int>("FiliereIdFiliere")
                        .HasColumnType("integer");

                    b.Property<string>("Groupe")
                        .HasColumnType("text");

                    b.Property<int>("IdClasse")
                        .HasColumnType("integer");

                    b.Property<int>("IdEtudiant")
                        .HasColumnType("integer");

                    b.Property<int>("IdFiliere")
                        .HasColumnType("integer");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasIndex("ClasseIdClasse");

                    b.HasIndex("FiliereIdFiliere");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Etudiants", (string)null);
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Professeur", b =>
                {
                    b.HasBaseType("BackendCoursFlow.Models.Utilisateurs.Utilisateur");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdProf")
                        .HasColumnType("integer");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Professeurs", (string)null);
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Responsable", b =>
                {
                    b.HasBaseType("BackendCoursFlow.Models.Utilisateurs.Utilisateur");

                    b.Property<int>("IdResp")
                        .HasColumnType("integer");

                    b.ToTable("Responsables", (string)null);
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Classe", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Filiere", "Filiere")
                        .WithMany("Classes")
                        .HasForeignKey("IdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiere");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Disponibilite", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Professeur", "Professeur")
                        .WithMany("Disponibilites")
                        .HasForeignKey("IdProf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professeur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Cours", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Pedagogies.EmploiDuTemps", "EmploiDuTemps")
                        .WithMany("Cours")
                        .HasForeignKey("EmploiDuTempsIdEmploi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Classe", "Classe")
                        .WithMany("Cours")
                        .HasForeignKey("IdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Pedagogies.Matiere", "Matiere")
                        .WithMany("Cours")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Professeur", "Professeur")
                        .WithMany("Cours")
                        .HasForeignKey("IdProf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Salles.Salle", "Salle")
                        .WithMany("Cours")
                        .HasForeignKey("IdSalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("EmploiDuTemps");

                    b.Navigation("Matiere");

                    b.Navigation("Professeur");

                    b.Navigation("Salle");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Prerequis", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Pedagogies.Matiere", "Matiere")
                        .WithMany("Prerequis")
                        .HasForeignKey("IdMatiere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Pedagogies.Matiere", "MatierePrerequis")
                        .WithMany()
                        .HasForeignKey("IdMatierePrerequis")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Matiere");

                    b.Navigation("MatierePrerequis");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Admin", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("BackendCoursFlow.Models.Utilisateurs.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Etudiant", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("ClasseIdClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.EmploiDuTemps.Filiere", "Filiere")
                        .WithMany("Etudiants")
                        .HasForeignKey("FiliereIdFiliere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("BackendCoursFlow.Models.Utilisateurs.Etudiant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");

                    b.Navigation("Filiere");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Professeur", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("BackendCoursFlow.Models.Utilisateurs.Professeur", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Responsable", b =>
                {
                    b.HasOne("BackendCoursFlow.Models.Utilisateurs.Utilisateur", null)
                        .WithOne()
                        .HasForeignKey("BackendCoursFlow.Models.Utilisateurs.Responsable", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Classe", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.EmploiDuTemps.Filiere", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Etudiants");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.EmploiDuTemps", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Pedagogies.Matiere", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Prerequis");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Salles.Salle", b =>
                {
                    b.Navigation("Cours");
                });

            modelBuilder.Entity("BackendCoursFlow.Models.Utilisateurs.Professeur", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Disponibilites");
                });
#pragma warning restore 612, 618
        }
    }
}
